### ISSUE TITLE
[Meta] mrwonko's roadmap

### ISSUE THREAD

**Issue by mrwonko** [JACoders/OpenJK#818]
This is mostly a post for me to keep track of my tasks and how I prioritize them. Not entirely sure this is the best place for that, but since Github so helpfully links issues I might as well...

So this is what I'm thinking about tackling next, in decreasing priority:

- [ ] #706 Add an OpenJK archive format; this is particularly important for compatibility reasons so we can intelligently decide whether a mod is supported or not
- [ ] #141 Create crash dumps & set up a source server
- [ ] #739 Make save games cross-platform and cross-architecture
- [ ] #754 Create a stable SP Mod ABI
- [ ] #746 Verify JK2SP works correctly
- [ ] #755 Create a nice OpenJK Website for Release 1.0
- [ ] #639 / #627 Make installation easier (related: #600, #362)
- [ ] #186 Release 1.0
- [ ] Verify mod code compiles as C++
- [ ] Write a mod manager with an open distributed backend (akin to Linux packet managers)
- [ ] Clean up all the code. While this is pretty important, it's also a huge task without any immediate benefits. Includes/related: #749, #756, #753, #719, #715, #650, #611, #508, #503, #451, #384, #354, #323, #313, #312, #277, #92
- [ ] Write a fast and clean OpenGL ES(2?) renderer with the same features as vanilla (related: #475)

**Comment by RostakaGmfun** [comment]
Hi! Can I take some of the "cleanup " tickets?

**Comment by xycaleth** [comment]
Go ahead :) Pick an issue and just go with it. It might be worth mentioning in the relevant issue how you plan to tidy up the code in question before you get started to prevent cases where you've submitted a PR, only for us to say we don't like how it's been done!
